--------------------------------------------------------
--  File created - Thursday-March-16-2017   
--------------------------------------------------------

CREATE USER C##LEGBOOK IDENTIFIED BY STUDENT;
GRANT CONNECT, RESOURCE, DBA TO C##LEGBOOK;
GRANT CREATE SESSION GRANT ANY PRIVILEGE TO  C##LEGBOOK;

--------------------------------------------------------
--  DDL for Table FRIENDS
--------------------------------------------------------

  CREATE TABLE "C##LEGBOOK"."FRIENDS" 
   (	"USERNAME1" VARCHAR2(20 BYTE), 
	"USERNAME2" VARCHAR2(20 BYTE), 
	"FRIENDTYPE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##LEGBOOK"."FRIENDS"."FRIENDTYPE" IS '0 = friend, 1 = best friend, 2 = family ...';
--------------------------------------------------------
--  DDL for Table GROUPMESSAGES
--------------------------------------------------------

  CREATE TABLE "C##LEGBOOK"."GROUPMESSAGES" 
   (	"MESSAGES_ID" NUMBER(*,0), 
	"GROUP_ID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(50 CHAR), 
	"MESSAGE_TEXT" VARCHAR2(500 CHAR), 
	"DATA_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GROUPS
--------------------------------------------------------

  CREATE TABLE "C##LEGBOOK"."GROUPS" 
   (	"GROUP_ID" NUMBER(*,0), 
	"GROUP_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GROUP_APPARTENANCE
--------------------------------------------------------

  CREATE TABLE "C##LEGBOOK"."GROUP_APPARTENANCE" 
   (	"USERNAME" VARCHAR2(20 BYTE), 
	"GROUP_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POSTS
--------------------------------------------------------

  CREATE TABLE "C##LEGBOOK"."POSTS" 
   (	"POST_ID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"POST_TYPE" VARCHAR2(20 BYTE), 
	"POST_TITLE" VARCHAR2(20 BYTE), 
	"POST_TEXT" VARCHAR2(500 BYTE), 
	"POST_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRIVATEMESSAGES
--------------------------------------------------------

  CREATE TABLE "C##LEGBOOK"."PRIVATEMESSAGES" 
   (	"PM_ID" NUMBER(*,0), 
	"SENDER" VARCHAR2(20 CHAR), 
	"RECIEVER" VARCHAR2(20 CHAR), 
	"MESSAGE_TEXT" VARCHAR2(500 CHAR), 
	"MESSAGE_DATA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "C##LEGBOOK"."USERS" 
   (	"USERNAME" VARCHAR2(50 CHAR), 
	"DISPLAY_NAME" VARCHAR2(50 CHAR), 
	"EMAIL" VARCHAR2(50 CHAR), 
	"DATE_CREATED" DATE, 
	"PASSHASH" VARCHAR2(128 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GROUPMESSAGES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##LEGBOOK"."GROUPMESSAGES_PK" ON "C##LEGBOOK"."GROUPMESSAGES" ("MESSAGES_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GROUPS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##LEGBOOK"."GROUPS_PK" ON "C##LEGBOOK"."GROUPS" ("GROUP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index POSTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##LEGBOOK"."POSTS_PK" ON "C##LEGBOOK"."POSTS" ("POST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRIVATEMESSAGES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##LEGBOOK"."PRIVATEMESSAGES_PK" ON "C##LEGBOOK"."PRIVATEMESSAGES" ("PM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##LEGBOOK"."USERS_PK" ON "C##LEGBOOK"."USERS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USERS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##LEGBOOK"."USERS_UK1" ON "C##LEGBOOK"."USERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FRIENDS
--------------------------------------------------------

  ALTER TABLE "C##LEGBOOK"."FRIENDS" MODIFY ("FRIENDTYPE" NOT NULL ENABLE);
  ALTER TABLE "C##LEGBOOK"."FRIENDS" MODIFY ("USERNAME2" NOT NULL ENABLE);
  ALTER TABLE "C##LEGBOOK"."FRIENDS" MODIFY ("USERNAME1" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GROUPMESSAGES
--------------------------------------------------------

  ALTER TABLE "C##LEGBOOK"."GROUPMESSAGES" ADD CONSTRAINT "GROUPMESSAGES_PK" PRIMARY KEY ("MESSAGES_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##LEGBOOK"."GROUPMESSAGES" MODIFY ("DATA_CREATED" NOT NULL ENABLE);
  ALTER TABLE "C##LEGBOOK"."GROUPMESSAGES" MODIFY ("MESSAGE_TEXT" NOT NULL ENABLE);
  ALTER TABLE "C##LEGBOOK"."GROUPMESSAGES" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "C##LEGBOOK"."GROUPMESSAGES" MODIFY ("GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "C##LEGBOOK"."GROUPMESSAGES" MODIFY ("MESSAGES_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GROUPS
--------------------------------------------------------

  ALTER TABLE "C##LEGBOOK"."GROUPS" ADD CONSTRAINT "GROUPS_PK" PRIMARY KEY ("GROUP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##LEGBOOK"."GROUPS" MODIFY ("GROUP_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##LEGBOOK"."GROUPS" MODIFY ("GROUP_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GROUP_APPARTENANCE
--------------------------------------------------------

  ALTER TABLE "C##LEGBOOK"."GROUP_APPARTENANCE" MODIFY ("GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "C##LEGBOOK"."GROUP_APPARTENANCE" MODIFY ("USERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POSTS
--------------------------------------------------------

  ALTER TABLE "C##LEGBOOK"."POSTS" ADD CONSTRAINT "POSTS_PK" PRIMARY KEY ("POST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##LEGBOOK"."POSTS" MODIFY ("POST_DATE" NOT NULL ENABLE);
  ALTER TABLE "C##LEGBOOK"."POSTS" MODIFY ("POST_TEXT" NOT NULL ENABLE);
  ALTER TABLE "C##LEGBOOK"."POSTS" MODIFY ("POST_TITLE" NOT NULL ENABLE);
  ALTER TABLE "C##LEGBOOK"."POSTS" MODIFY ("POST_TYPE" NOT NULL ENABLE);
  ALTER TABLE "C##LEGBOOK"."POSTS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "C##LEGBOOK"."POSTS" MODIFY ("POST_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRIVATEMESSAGES
--------------------------------------------------------

  ALTER TABLE "C##LEGBOOK"."PRIVATEMESSAGES" ADD CONSTRAINT "PRIVATEMESSAGES_PK" PRIMARY KEY ("PM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##LEGBOOK"."PRIVATEMESSAGES" MODIFY ("MESSAGE_DATA" NOT NULL ENABLE);
  ALTER TABLE "C##LEGBOOK"."PRIVATEMESSAGES" MODIFY ("MESSAGE_TEXT" NOT NULL ENABLE);
  ALTER TABLE "C##LEGBOOK"."PRIVATEMESSAGES" MODIFY ("RECIEVER" NOT NULL ENABLE);
  ALTER TABLE "C##LEGBOOK"."PRIVATEMESSAGES" MODIFY ("SENDER" NOT NULL ENABLE);
  ALTER TABLE "C##LEGBOOK"."PRIVATEMESSAGES" MODIFY ("PM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "C##LEGBOOK"."USERS" ADD CONSTRAINT "USERS_UK1" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##LEGBOOK"."USERS" MODIFY ("PASSHASH" NOT NULL ENABLE);
  ALTER TABLE "C##LEGBOOK"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##LEGBOOK"."USERS" MODIFY ("DISPLAY_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##LEGBOOK"."USERS" MODIFY ("DATE_CREATED" NOT NULL ENABLE);
  ALTER TABLE "C##LEGBOOK"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "C##LEGBOOK"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FRIENDS
--------------------------------------------------------

  ALTER TABLE "C##LEGBOOK"."FRIENDS" ADD CONSTRAINT "FRIENDS_FK1" FOREIGN KEY ("USERNAME1")
	  REFERENCES "C##LEGBOOK"."USERS" ("USERNAME") ENABLE;
  ALTER TABLE "C##LEGBOOK"."FRIENDS" ADD CONSTRAINT "FRIENDS_FK2" FOREIGN KEY ("USERNAME2")
	  REFERENCES "C##LEGBOOK"."USERS" ("USERNAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GROUPMESSAGES
--------------------------------------------------------

  ALTER TABLE "C##LEGBOOK"."GROUPMESSAGES" ADD CONSTRAINT "GROUP_ID" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "C##LEGBOOK"."GROUPS" ("GROUP_ID") ENABLE;
  ALTER TABLE "C##LEGBOOK"."GROUPMESSAGES" ADD CONSTRAINT "USERNAME" FOREIGN KEY ("USERNAME")
	  REFERENCES "C##LEGBOOK"."USERS" ("USERNAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GROUP_APPARTENANCE
--------------------------------------------------------

  ALTER TABLE "C##LEGBOOK"."GROUP_APPARTENANCE" ADD CONSTRAINT "GROUP_APPARTENANCE_FK1" FOREIGN KEY ("USERNAME")
	  REFERENCES "C##LEGBOOK"."USERS" ("USERNAME") ENABLE;
  ALTER TABLE "C##LEGBOOK"."GROUP_APPARTENANCE" ADD CONSTRAINT "GROUP_APPARTENANCE_FK2" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "C##LEGBOOK"."GROUPS" ("GROUP_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRIVATEMESSAGES
--------------------------------------------------------

  ALTER TABLE "C##LEGBOOK"."PRIVATEMESSAGES" ADD CONSTRAINT "RECIEVER" FOREIGN KEY ("RECIEVER")
	  REFERENCES "C##LEGBOOK"."USERS" ("USERNAME") ENABLE;
  ALTER TABLE "C##LEGBOOK"."PRIVATEMESSAGES" ADD CONSTRAINT "SENDER" FOREIGN KEY ("SENDER")
	  REFERENCES "C##LEGBOOK"."USERS" ("USERNAME") ENABLE;
